let colorGrid = ['WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE',
'WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE','WHITE']

let selected = 'WHITE'


module.exports = {colorGrid, selected}
